# Generated by Django 2.0.5 on 2020-03-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subdistricts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hprice', models.IntegerField(blank=True, null=True)),
                ('weidu_jingdu', models.CharField(blank=True, max_length=255, null=True)),
                ('ting', models.IntegerField(blank=True, null=True)),
                ('shi', models.IntegerField(blank=True, null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('e', models.IntegerField(blank=True, db_column='E', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('t2', models.FloatField(blank=True, db_column='T2', null=True)),
                ('delta_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('poi_address', models.CharField(blank=True, max_length=255, null=True)),
                ('poi_jingdu', models.CharField(blank=True, max_length=255, null=True)),
                ('poi_weidu', models.CharField(blank=True, max_length=255, null=True)),
                ('poi_type', models.CharField(blank=True, max_length=255, null=True)),
                ('poi_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('poi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'poi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('hid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('hyuanid', models.CharField(blank=True, max_length=255, null=True)),
                ('htitle', models.TextField(blank=True, null=True)),
                ('hsmallimageurl', models.CharField(blank=True, max_length=255, null=True)),
                ('hurl', models.CharField(blank=True, max_length=255, null=True)),
                ('himagedir', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '房子信息',
                'verbose_name_plural': '房子信息',
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='Himageurl',
            fields=[
                ('hid', models.OneToOneField(db_column='hid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='houses.House')),
                ('hbigimageurl', models.CharField(max_length=255)),
                ('himageorder', models.IntegerField(blank=True, null=True)),
                ('isdownload', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'himageurl',
            },
        ),
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('hid', models.OneToOneField(db_column='hid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='houses.House')),
                ('hprice', models.IntegerField(blank=True, null=True)),
                ('hdirection', models.CharField(blank=True, max_length=255, null=True)),
                ('htype', models.CharField(blank=True, max_length=255, null=True)),
                ('harea', models.IntegerField(blank=True, null=True)),
                ('hfloor', models.CharField(blank=True, max_length=255, null=True)),
                ('hpubdate', models.CharField(blank=True, max_length=255, null=True)),
                ('hcontact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hpredictprice', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '房子详细',
                'verbose_name_plural': '房子详细',
                'db_table': 'house_detail',
            },
        ),
        migrations.CreateModel(
            name='HouseFacility',
            fields=[
                ('hid', models.OneToOneField(db_column='hid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='houses.House')),
                ('washer', models.IntegerField(blank=True, null=True)),
                ('tv', models.IntegerField(blank=True, db_column='TV', null=True)),
                ('airconditioner', models.IntegerField(blank=True, null=True)),
                ('freezer', models.IntegerField(blank=True, null=True)),
                ('heating', models.IntegerField(blank=True, null=True)),
                ('wifi', models.IntegerField(blank=True, null=True)),
                ('lift', models.IntegerField(blank=True, null=True)),
                ('gas', models.IntegerField(blank=True, null=True)),
                ('water_heater', models.IntegerField(blank=True, null=True)),
                ('parkinglot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house_facility',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='subdistrictid',
            field=models.ForeignKey(blank=True, db_column='subdistrictid', null=True, on_delete=django.db.models.deletion.CASCADE, to='subdistricts.Subdistrict'),
        ),
        migrations.AlterUniqueTogether(
            name='himageurl',
            unique_together={('hid', 'hbigimageurl')},
        ),
    ]
