# Generated by Django 2.0.5 on 2019-03-20 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 16, 40, 37, 831573), verbose_name='发送时间'),
        ),
    ]
