# Generated by Django 2.0.5 on 2019-03-21 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190320_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 10, 21, 0, 521603), verbose_name='发送时间'),
        ),
    ]
