# Generated by Django 2.0.5 on 2019-07-03 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190321_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 23, 0, 58, 38656), verbose_name='发送时间'),
        ),
    ]
