# Generated by Django 2.0.5 on 2019-07-03 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190703_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 23, 3, 11, 482818), verbose_name='发送时间'),
        ),
    ]
