# Generated by Django 2.0.5 on 2020-03-28 21:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190703_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrefer',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('t2_t1', models.FloatField(blank=True, db_column='T2_T1', null=True)),
                ('l_t1', models.FloatField(blank=True, db_column='L_T1', null=True)),
                ('e_t1', models.FloatField(blank=True, db_column='E_T1', null=True)),
                ('h_t1', models.FloatField(blank=True, db_column='H_T1', null=True)),
                ('g_t1', models.FloatField(blank=True, db_column='G_T1', null=True)),
                ('v1_t1', models.FloatField(blank=True, db_column='V1_T1', null=True)),
                ('v2_t1', models.FloatField(blank=True, db_column='V2_T1', null=True)),
                ('l_t2', models.FloatField(blank=True, db_column='L_T2', null=True)),
                ('e_t2', models.FloatField(blank=True, db_column='E_T2', null=True)),
                ('h_t2', models.FloatField(blank=True, db_column='H_T2', null=True)),
                ('g_t2', models.FloatField(blank=True, db_column='G_T2', null=True)),
                ('v1_t2', models.FloatField(blank=True, db_column='V1_T2', null=True)),
                ('v2_t2', models.FloatField(blank=True, db_column='V2_T2', null=True)),
                ('e_l', models.FloatField(blank=True, db_column='E_L', null=True)),
                ('h_l', models.FloatField(blank=True, db_column='H_L', null=True)),
                ('g_l', models.FloatField(blank=True, db_column='G_L', null=True)),
                ('v1_l', models.FloatField(blank=True, db_column='V1_L', null=True)),
                ('v2_l', models.FloatField(blank=True, db_column='V2_L', null=True)),
                ('h_e', models.FloatField(blank=True, db_column='H_E', null=True)),
                ('g_e', models.FloatField(blank=True, db_column='G_E', null=True)),
                ('v1_e', models.FloatField(blank=True, db_column='V1_E', null=True)),
                ('v2_e', models.FloatField(blank=True, db_column='V2_E', null=True)),
                ('g_h', models.FloatField(blank=True, db_column='G_H', null=True)),
                ('v1_h', models.FloatField(blank=True, db_column='V1_H', null=True)),
                ('v2_v1', models.FloatField(blank=True, db_column='V2_V1', null=True)),
                ('b2_h', models.FloatField(blank=True, db_column='B2_H', null=True)),
            ],
            options={
                'db_table': 'user_prefer',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 21, 41, 6, 237130), verbose_name='发送时间'),
        ),
    ]
