# Generated by Django 2.0.5 on 2020-03-28 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200328_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 23, 18, 27, 576836), verbose_name='发送时间'),
        ),
    ]
