# Generated by Django 2.0.5 on 2020-03-29 17:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200328_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('weight_t1', models.FloatField()),
                ('weight_t2', models.FloatField()),
                ('weight_v1', models.FloatField()),
                ('weight_v2', models.FloatField()),
                ('weight_g', models.FloatField()),
                ('weight_l', models.FloatField()),
                ('weight_h', models.FloatField()),
                ('weight_e', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_weight',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 17, 33, 7, 26655), verbose_name='发送时间'),
        ),
    ]
